# Generated by Django 5.1.4 on 2026-04-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professioniste', '0002_add_data_nascita_e_verifica'),
    ]

    operations = [
        migrations.CreateModel(
            name='PianoAbbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('standard', 'Abbonamento standard'), ('evidenza', 'Abbonamento evidenza')], db_index=True, max_length=20)),
                ('nome', models.CharField(help_text='Es. "7 giorni", "Extra Day".', max_length=100)),
                ('durata_giorni', models.PositiveIntegerField()),
                ('prezzo_centesimi', models.PositiveIntegerField(help_text='Es. 1990 per 19,90 €.', verbose_name='Prezzo (centesimi €)')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('attivo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Piano abbonamento',
                'verbose_name_plural': 'Piani abbonamento',
                'ordering': ['tipo', 'ordine', 'durata_giorni'],
            },
        ),
        migrations.CreateModel(
            name='Abbonamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('in_attesa', 'In attesa di pagamento'), ('attivo', 'Attivo'), ('scaduto', 'Scaduto'), ('annullato', 'Annullato')], db_index=True, default='in_attesa', max_length=20)),
                ('importo_centesimi', models.PositiveIntegerField(help_text="Snapshot del prezzo al momento dell'acquisto.", verbose_name='Importo (centesimi €)')),
                ('inizio', models.DateTimeField(blank=True, null=True)),
                ('scadenza', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mock', 'Mock (sviluppo)')], max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('professionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abbonamenti', to='professioniste.professionista')),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abbonamenti', to='abbonamenti.pianoabbonamento')),
            ],
            options={
                'verbose_name': 'Abbonamento',
                'verbose_name_plural': 'Abbonamenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
