# Generated by Django 5.1.4 on 2026-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbonamenti', '0002_seed_piani'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Early Bird', help_text='Nome visualizzato (informativo).', max_length=80)),
                ('attiva', models.BooleanField(default=False, help_text='Disattiva qui per fermare la promozione anche prima della scadenza.')),
                ('scadenza', models.DateTimeField(help_text='Data e ora di fine promozione. Dopo questo istante lo sconto non viene più applicato.')),
            ],
            options={
                'verbose_name': 'Promozione',
                'verbose_name_plural': 'Promozione',
            },
        ),
        migrations.AddField(
            model_name='pianoabbonamento',
            name='sconto_percentuale',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentuale di sconto applicata se la Promozione globale è attiva. 0 = nessuno sconto.', verbose_name='Sconto Early Bird (%)'),
        ),
    ]
