# Generated by Django 5.1.4 on 2026-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbonamenti', '0003_promozione_pianoabbonamento_sconto_percentuale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodicePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.SlugField(help_text='Slug del link (es. "BENVENUTO50"). Solo lettere/numeri/trattini, niente spazi.', unique=True)),
                ('nome', models.CharField(default='Sconto link', help_text='Nome interno per ricordarti a cosa serve (visibile solo qui).', max_length=80)),
                ('sconto_percentuale', models.PositiveSmallIntegerField(help_text='Percentuale di sconto applicata su qualunque piano (0-100).')),
                ('attivo', models.BooleanField(default=True, help_text='Disattiva per fermare il codice anche prima della scadenza.')),
                ('scadenza', models.DateTimeField(blank=True, help_text='Opzionale: data di scadenza. Se vuoto, il codice non scade mai.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Codice sconto (link)',
                'verbose_name_plural': 'Codici sconto (link)',
                'ordering': ['-created_at'],
            },
        ),
    ]
