# Generated by Django 5.1.4 on 2026-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbonamenti', '0004_codicepromo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codicepromo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Codice referral', 'verbose_name_plural': 'Codici referral'},
        ),
        migrations.AlterField(
            model_name='codicepromo',
            name='codice',
            field=models.SlugField(help_text='Codice digitato dall\'utente (es. "BENVENUTO50"). Solo lettere/numeri/trattini, niente spazi.', unique=True),
        ),
        migrations.AlterField(
            model_name='codicepromo',
            name='nome',
            field=models.CharField(default='Codice referral', help_text='Nome interno per ricordarti a cosa serve (visibile solo qui).', max_length=80),
        ),
    ]
