# Generated by Django 5.1.4 on 2026-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posizione', models.CharField(choices=[('homepage_middle', 'Homepage — tra "Le più apprezzate" e "Vicino a te"')], db_index=True, help_text='Dove viene mostrato il banner.', max_length=50, verbose_name='Posizione')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('button_testo', models.CharField(blank=True, help_text='Lascia vuoto per non mostrare il bottone.', max_length=100, verbose_name='Testo bottone')),
                ('button_link', models.URLField(blank=True, help_text='URL completo (es. https://… o mailto:…).', verbose_name='Link bottone')),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Banner con ordine più basso vengono mostrati per primi a parità di posizione.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['ordine', '-updated_at'],
            },
        ),
    ]
