# Generated by Django 5.1.4 on 2026-04-28 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_seed_default_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL completo (es. https://…, mailto:… oppure tel:…).', max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto', 'tel'])], verbose_name='Link bottone'),
        ),
    ]
