# Generated by Django 5.1.4 on 2026-04-28 13:17

import apps.banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_banner_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, help_text='URL completo (es. https://…, mailto:… oppure tel:…).', max_length=500, validators=[apps.banners.models.validate_button_link], verbose_name='Link bottone'),
        ),
    ]
