# Generated by Django 5.1.4 on 2026-06-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_banner_copy_escort'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, default='', help_text='Titolo della sezione hero (es. "Le migliori escort a 5 stelle"). Lascia vuoto per usare il default.', max_length=200)),
                ('sottotitolo', models.TextField(blank=True, default='', help_text='Frase descrittiva sotto al titolo. Lascia vuoto per usare il default.')),
                ('immagine', models.ImageField(blank=True, help_text="Immagine di sfondo. Lascia vuoto per usare l'immagine di default del sito.", null=True, upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero homepage',
                'verbose_name_plural': 'Hero homepage',
            },
        ),
    ]
