# Generated by Django 5.1.4 on 2026-06-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_create_hero_singleton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosettings',
            name='immagine',
            field=models.ImageField(blank=True, help_text="Immagine di sfondo della sezione hero. Lascia vuoto per usare l'immagine di default (hero-home.png).", null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='sottotitolo',
            field=models.TextField(blank=True, default='', help_text='Frase descrittiva sotto al titolo. Lascia vuoto per usare il default: "Scopri le migliori escort vicino a te. Sfoglia le schede, leggi le recensioni e trova la escort perfetta per te in pochi click!".'),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='titolo',
            field=models.CharField(blank=True, default='', help_text='Titolo della sezione hero. Lascia vuoto per usare il default: "Le migliori escort a 5 stelle" (con la parola "escort" evidenziata in rosa). Se compili qui, il default viene sostituito col tuo testo (senza l\'evidenziato).', max_length=200),
        ),
    ]
