# Generated by Django 5.1.4 on 2026-04-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professioniste', '0009_professionista_telegram_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SbloccoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo_centesimi', models.PositiveIntegerField(default=190)),
                ('attivo', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('mock', 'Mock (sviluppo)')], max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sblocchi_social_da', to='professioniste.professionista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sblocchi_social', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sblocco social',
                'verbose_name_plural': 'Sblocchi social',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'professionista', 'attivo'], name='sblocchi_sb_user_id_06b619_idx')],
            },
        ),
    ]
