# Generated by Django 5.1.4 on 2026-04-30 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('abbonamento_scaduto', 'Abbonamento scaduto'), ('abbonamento_in_scadenza', 'Abbonamento in scadenza'), ('generico', 'Generico')], db_index=True, default='generico', max_length=40)),
                ('titolo', models.CharField(max_length=200)),
                ('messaggio', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Path interno (es. "/abbonamento") o URL completo dove portare l\'utente al click.', max_length=500)),
                ('letta', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifica',
                'verbose_name_plural': 'Notifiche',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'letta', '-created_at'], name='notifiche_n_user_id_e8c588_idx')],
            },
        ),
    ]
