# Generated by Django 5.1.4 on 2026-04-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professioniste', '0006_remove_professionista_mi_trovo_qui_aggiornato_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferito_da', to='professioniste.professionista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferiti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferito',
                'verbose_name_plural': 'Preferiti',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'professionista')},
            },
        ),
    ]
