# Generated by Django 5.1.4 on 2026-03-25 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('massaggi', 'Massaggi'), ('yoga', 'Yoga'), ('relax', 'Relax')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Professionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('via', models.CharField(max_length=500, verbose_name='Via / Indirizzo')),
                ('cap', models.CharField(max_length=10, verbose_name='CAP')),
                ('citta', models.CharField(max_length=200, verbose_name='Città')),
                ('provincia', models.CharField(max_length=2, verbose_name='Provincia (sigla)')),
                ('nazione', models.CharField(default='Italia', max_length=100, verbose_name='Stato / Nazione')),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('foto_profilo', models.ImageField(upload_to='professioniste/profilo/')),
                ('documento_fronte', models.ImageField(upload_to='professioniste/documenti/')),
                ('documento_retro', models.ImageField(upload_to='professioniste/documenti/')),
                ('stato_approvazione', models.CharField(choices=[('in_attesa', 'In attesa di verifica'), ('approvata', 'Approvata'), ('rifiutata', 'Rifiutata')], default='in_attesa', max_length=20)),
                ('privacy_accettata', models.BooleanField(default=False)),
                ('termini_accettati', models.BooleanField(default=False)),
                ('visualizzazioni', models.PositiveIntegerField(default=0)),
                ('click_telefono', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professioniste', to='professioniste.categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='professioniste', to='professioniste.tag')),
            ],
            options={
                'verbose_name_plural': 'Professioniste',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoProfessionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='professioniste/galleria/')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('professionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='professioniste.professionista')),
            ],
            options={
                'verbose_name_plural': 'Foto professioniste',
                'ordering': ['ordine'],
            },
        ),
    ]
