# Generated by Django 5.1.4 on 2026-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='data_nascita',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='data_verifica',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data verifica età'),
        ),
    ]
