# Generated by Django 5.1.4 on 2026-04-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0002_add_data_nascita_e_verifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_aggiornato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_attivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_citta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_indirizzo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionista',
            name='mi_trovo_qui_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
