# Generated by Django 5.1.4 on 2026-04-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0003_professionista_mi_trovo_qui_aggiornato_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Facebook (username o nome pagina)'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram (username)'),
        ),
    ]
