# Generated by Django 5.1.4 on 2026-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0004_professionista_facebook_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionista',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='instagram_username',
        ),
        migrations.AddField(
            model_name='professionista',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Facebook'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Instagram'),
        ),
    ]
