# Generated by Django 5.1.4 on 2026-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0005_remove_professionista_facebook_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_aggiornato_at',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_attivo',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_citta',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_indirizzo',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_lat',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='mi_trovo_qui_lng',
        ),
        migrations.AddField(
            model_name='professionista',
            name='cap_privato',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CAP (privato)'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='citta_privata',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Città (privata)'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='indirizzo_pubblico_aggiornato_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionista',
            name='nazione_privata',
            field=models.CharField(blank=True, default='Italia', max_length=100, verbose_name='Stato / Nazione (privata)'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='provincia_privata',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Provincia (sigla, privata)'),
        ),
        migrations.AddField(
            model_name='professionista',
            name='via_privata',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Via / Indirizzo (privato)'),
        ),
        migrations.AlterField(
            model_name='professionista',
            name='cap',
            field=models.CharField(max_length=10, verbose_name='CAP (pubblico)'),
        ),
        migrations.AlterField(
            model_name='professionista',
            name='citta',
            field=models.CharField(max_length=200, verbose_name='Città (pubblica)'),
        ),
        migrations.AlterField(
            model_name='professionista',
            name='nazione',
            field=models.CharField(default='Italia', max_length=100, verbose_name='Stato / Nazione (pubblica)'),
        ),
        migrations.AlterField(
            model_name='professionista',
            name='provincia',
            field=models.CharField(max_length=2, verbose_name='Provincia (sigla, pubblica)'),
        ),
        migrations.AlterField(
            model_name='professionista',
            name='via',
            field=models.CharField(max_length=500, verbose_name='Via / Indirizzo (pubblico)'),
        ),
    ]
