# Generated by Django 5.1.4 on 2026-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0006_remove_professionista_mi_trovo_qui_aggiornato_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='tiktok_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link TikTok'),
        ),
    ]
