# Generated by Django 5.1.4 on 2026-04-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0007_professionista_tiktok_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionista',
            name='cap_privato',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='citta_privata',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='nazione_privata',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='provincia_privata',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='via_privata',
        ),
        migrations.RemoveField(
            model_name='professionista',
            name='visualizzazioni',
        ),
    ]
