# Generated by Django 5.1.4 on 2026-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0008_remove_professionista_cap_privato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link Telegram'),
        ),
    ]
