# Generated by Django 5.1.4 on 2026-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0009_professionista_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='stato',
            field=models.CharField(blank=True, default='', help_text='Frase breve mostrata sotto il nome nella card (es. "Sempre disponibile").', max_length=80, verbose_name='Stato'),
        ),
    ]
