# Generated by Django 5.1.4 on 2026-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professioniste', '0010_professionista_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionista',
            name='onlyfans_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link OnlyFans'),
        ),
    ]
